const enum CachedKeys {
  POKEMON_COLORS = 'POKEMON_COLORS',
  POKEMON_FORMS = 'POKEMON_FORMS',
  POKEMON_FORM_DETAILS = 'POKEMON_FORM_DETAILS',
  POKEMON_MACHINES = 'POKEMON_MACHINES',
}

export default CachedKeys;
